# Generated by Django 4.2.6 on 2023-10-14 15:19

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_psychologist_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='username',
            field=models.CharField(error_messages={'unique': 'Este nombre de usuario ya existe.'}, help_text='Rquerido. 30 caracteres o menos. Solo letras, numeros y @/./+/-/_.', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nombre de usuario'),
        ),
    ]
